Port source from pyrophobia
ateliercw/AnglePanGestureRecognizer pull request #4
Opened 2017-05-21 20:33 UTC by mattThousand

<img width="1168" alt="screen shot 2017-05-16 at 5 25 16 pm" src="https://cloud.githubusercontent.com/assets/2637355/26287153/3bf0e15a-3e43-11e7-8640-4782da33afc1.png">

2017-05-21 20:38 UTC, mattThousand commented
@ateliercw a not-completely-baked PR for you. Couple of questions I have at the moment:

`1. Error handling`: do you have a preferred approach here? want to guard against things like `allowedAngles.count == 0` and provide some useful debug messaging 

`2.Scope`: The only public class in the framework atm is `AnglePanGestureRecognizer`. All of the grid wizardry is in the example project. This is the vision for the framework, is that correct?

2017-05-28 20:24 UTC, ateliercw requested changes
Would like to see it animate with the motions like pyrophobia too, but a great start. Lots of minor style feedback.

2017-05-28 20:24 UTC, ateliercw commented on AnglePanGestureRecognizer/Recognizers/AnglePanGestureRecognizer.swift
> +
Swiftlint is whining about trailing whitespace

2017-05-28 20:24 UTC, ateliercw commented on AnglePanGestureRecognizer/Recognizers/AnglePanGestureRecognizer.swift
> +public protocol AnglePanGestureRecognizerDelegate {
this should be class bound to make everything that conforms to it be weak-able (swiftlint)

2017-05-28 20:24 UTC, ateliercw commented on AnglePanGestureRecognizer/Recognizers/AnglePanGestureRecognizer.swift
> +    var unlockedMoveDelegate: AnglePanGestureRecognizerDelegate?
delegates should be weak, because retain cycles. (swiftlint)

2017-05-28 20:24 UTC, ateliercw commented on AnglePanGestureRecognizer Example/Grid/Grid.swift
> +    static func generateBoard<T>(with generator: (GridPoint) -> T,
Swiftlint is whining about vertical parameter alignment, either put the whole thing on one line or disable the rule

2017-05-28 20:24 UTC, ateliercw commented on AnglePanGestureRecognizer Example/Extensions/ClosedCountableRange+Grid.swift
>      // swiftlint:disable:next large_tuple
delete this as the tuple is no longer large

2017-05-28 20:24 UTC, ateliercw commented on AnglePanGestureRecognizer Example/Grid/GridPoint.swift
> +    func angleInFlatArrangment(facing gridPoint: GridPoint) -> CGFloat? {
on a square grid there isn't a flat/pointy alignment, so this should probable just be `angle(facing:)`

2017-05-28 20:24 UTC, ateliercw commented on AnglePanGestureRecognizer Example/Grid/GridPoint.swift
> +    // Cube Coordinates
Remove the comment or change to cartesian coordinates

2017-05-28 20:24 UTC, ateliercw commented on AnglePanGestureRecognizer/Recognizers/AnglePanGestureRecognizer.swift
> +    /// Called when user's gesture exceeds the distance specified by unlockedMoveDistance
In Pyrophobia, unlockedMoveDistance is the "dead" zone where a move isn't yet snapped to a particular angle and the sprite moves freely. The move isn't committed until you release the sprite, at which point the game either commits the move, or unwinds the gesture and returns the sprite to it's original origin.

2017-05-28 20:24 UTC, ateliercw commented on AnglePanGestureRecognizer/Recognizers/AnglePanGestureRecognizer.swift
> +    fileprivate var maxAngleDifference: CGFloat { return CGFloat.pi / CGFloat(allowedAngles.count) }
this shouldn't be a computed value because it can be used to increase or reduce the sensitivity depending on library user preferences.

2017-05-28 20:24 UTC, ateliercw commented on AnglePanGestureRecognizer/Recognizers/AnglePanGestureRecognizer.swift
> +    var unlockedMoveDistance: CGFloat = 0
Leave the default at 5px

2017-05-28 20:24 UTC, ateliercw commented on AnglePanGestureRecognizer/Recognizers/AnglePanGestureRecognizer.swift
> +    public struct Options {
I'm not a fan of having an `Options` struct that's just used in the initialiser. I'm assuming this was done to work around swiftlint complaining about too many args, I'd rather just silence that particular warning that have to init an options to init a recogniser

2017-05-28 20:24 UTC, ateliercw commented on AnglePanGestureRecognizer/Recognizers/AnglePanGestureRecognizer.swift
> +        // Quadrant IV in the cartesian plane
Should be quadrant I

2017-05-28 20:24 UTC, ateliercw commented on AnglePanGestureRecognizer/Recognizers/AnglePanGestureRecognizer.swift
>          // Quadrant III in the cartesian plane
Should be quadrant II

2017-05-28 20:24 UTC, ateliercw commented on AnglePanGestureRecognizer/Recognizers/AnglePanGestureRecognizer.swift
>          // Quadrant I in the cartesian plane
Should be Quadrant IV

2017-05-28 20:24 UTC, ateliercw commented on AnglePanGestureRecognizer/Recognizers/AnglePanGestureRecognizer.swift
>          // Quadrant II in the cartesian plane
Should be quadrant III

2017-05-28 20:24 UTC, ateliercw commented on AnglePanGestureRecognizer/Recognizers/AnglePanGestureRecognizer.swift
>              self.angle = 0
Should probably assert if we ever return something not in the Cartesian plane

2017-05-28 20:24 UTC, ateliercw commented on AnglePanGestureRecognizer/Recognizers/AnglePanGestureRecognizer.swift
>          return CGPoint(x: s1, y: s2)
I find it odd these ended up switched, but the math moving with the object seems to work in app.

2017-05-28 20:24 UTC, ateliercw commented on AnglePanGestureRecognizer/Recognizers/AnglePanGestureRecognizer.swift
> +    public init(target: Any?,
This whole initialiser may be overkill, I can't think of a UIKit class that initialises with target, action, and delegate

2017-05-28 20:56 UTC, mattThousand commented on AnglePanGestureRecognizer/Recognizers/AnglePanGestureRecognizer.swift
> +    public init(target: Any?,
yeah, that was the reason I created a `Options` struct (to avoid an initializer with too many args).

2017-05-28 20:58 UTC, mattThousand commented on AnglePanGestureRecognizer/Recognizers/AnglePanGestureRecognizer.swift
> +    public init(target: Any?,
the thought was that it would force the user to define a few things up front and thus guard against having, say, and empty `allowedMoves` collection

2017-05-28 20:59 UTC, mattThousand commented on AnglePanGestureRecognizer/Recognizers/AnglePanGestureRecognizer.swift
> +    public init(target: Any?,
but you're right, it's certainly clunky. removing...

2017-05-28 21:16 UTC, mattThousand commented
@ateliercw back to you. `swiftLint` seems to be pacified? ...not seeing violations 🤷‍♂️

2017-08-11 20:32 UTC, closed without merging